name: Sync Repo Contents to S3 Bucket
on:
  push:
    branches:
      - main
env:
  bucket-name: bigdatabuddies-project-etl-scripts

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync reddit folder to S3 bucket
        run: aws s3 sync reddit s3://${{ env.bucket-name }}/reddit

      - name: Sync twitter folder to S3 bucket
        run: aws s3 sync twitter s3://${{ env.bucket-name }}/twitter

      - name: Sync dag folder to S3 bucket
        run: aws s3 sync twitter s3://${{ env.bucket-name }}/dags